#!/bin/sh
cd /usr/local/lib/
#preparando otras dependencias necesarias
#aptitude install libxml2-dev binutils
#GEOS
#wget http://download.osgeo.org/geos/geos-3.3.5.tar.bz2
#tar xjf geos-3.3.5.tar.bz2
#cd geos-3.3.5/
#./configure
#make
#make install
#cd ..
#PROJ4
#wget http://download.osgeo.org/proj/proj-4.8.0.tar.gz
#wget http://download.osgeo.org/proj/proj-datumgrid-1.5.tar.gz
#tar xzf proj-4.8.0.tar.gz
#cd proj-4.8.0/nad/
#tar xzf ../../proj-datumgrid-1.5.tar.gz
#cd ..
#./configure
#make
#make install
#cd ..
#gdal
#aptitude install gdal-bin python2.7-gdal libgdal-dev
#PostGIS
#wget http://postgis.refractions.net/download/postgis-2.0.1.tar.gz
#tar xzf postgis-2.0.1.tar.gz
#cd postgis-2.0.1
#./configure
#make
#make install
#cd ..
#Creando el template de postgis 2.0
sh /media/Archivos/Server/Tesis/scripts/create-template-postgis
